Repository Redline-Revealer/redline-revealer, pull requests merged in 2025-06, with the labels that each got.

#19 docs: add individual team role files to /docs
  docs/roles/ai-integration.md
  docs/roles/data-analyst.md
  docs/roles/devops.md
  docs/roles/frontend.md
  docs/roles/project-manager.md
Labels: documentation

#13 fix(ci): shorten line to satisfy flake8 E501
  src/app.py
Labels: bug

#14 fix(ci): resolve flake8 line length error
  src/app.py
Labels: bug

#24 Add branch protection workflow
  .github/workflows/branch-protection.yml
  src/app.py
Labels: codex

#27 Add .env.example template
  .env.example
Labels: codex

#31 Add placeholder structure
  src/agent/legal_agent.py
  src/app.py
  src/pages/about.py
  src/pages/assistant.py
  src/pages/map.py
  src/pages/welcome.py
  src/utils/file_utils.py
  tests/test_placeholder.py
Labels: codex

#36 test/fix-placeholder-formatting: Resolve Flake8 E302 linting error
  tests/test_placeholder.py
Labels: backend

#34 Add autopep8 pre-commit config
  .pre-commit-config.yaml
  tests/test_placeholder.py
Labels: codex

#29 Add AI Legal Agent with Prompt Logic and Retrieval
  agent/legal_agent.py
  data/blob_pdfs/Addressing-Heirs-Property-fl.pdf
  data/blob_pdfs/heirs-property-fact-sheet-fl-2024.pdf
  data/indexes/legal_docs_index/index.faiss
  data/indexes/legal_docs_index/index.pkl
  data/source_links.json
  data/state_links.json
  requirements.txt
  scripts/source_links.py
  src/app.py
  src/load_agent_documents.py
  src/prompt_handler.py
  src/ui_helpers.py
  src/utils/state_list.py
  tests/test_prompt_handler.py
Labels: AI/ML, backend

#28 Add flake8 config
  .flake8
Labels: codex

#20 Create README_HousingRiskAnalysis.md
  Data analysis/README_HousingRiskAnalysis.md
Labels: documentation
